[project]
name = "coppersmith"
description = "Functions for finding small roots of multivariate modular equations"
readme = "README.md"
version = "0.0.1"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = []
py-modules = ["coppersmith"]